name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build_upload:
    runs-on: ubuntu-latest
    permissions:
     actions: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: build
        run: ./make.sh prerelease
      - name: build
        run: |
          mkdir build
          cp ytarchive ytarchive.exe build/
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: ytarchive
          path: build/
